export const positions = [
  "back",
  "butterfly",
  "closed guard",
  "collar sleeve guard",
  "de la riva",
  "fifty fifty",
  "half guard (bottom)",
  "half guard (top)",
  "k guard",
  "knee on belly",
  "knee shield",
  "lasso guard",
  "mount",
  "north south",
  "north south kimura",
  "octopus guard",
  "reverse de la riva",
  "s mount",
  "saddle",
  "scarf hold",
  "seated",
  "spider guard",
  "side control",
  "single leg x",
  "x guard",
  "z guard",
];
